version: '3.9'

services:
  app:
    image: $CI_REGISTRY/$CI_PROJECT_PATH:${CI_COMMIT_SHORT_SHA}
    networks:
      - proxy_network
    ports:
      - ${SERVER_PORT}:80
    environment:
      APP_DEBUG:
      APP_ENV:
      APP_URL:
      APP_KEY:
      DB_CONNECTION:
      DB_HOST:
      DB_PORT:
      DB_DATABASE:
      DB_USERNAME:
      DB_PASSWORD:
      FILESYSTEM_DISK:
      QUEUE_CONNECTION:
      TWILIO_SID:
      TWILIO_AUTH_TOKEN:
      TWILIO_NUMBER:
      TWILIO_NOTIFY_SID:

  #  schedule-worker:
  #    image: $CI_REGISTRY/$CI_PROJECT_PATH:${CI_COMMIT_SHORT_SHA}
  #    networks:
  #      - proxy_network
  #    command: php artisan schedule:work
  #    environment:
  #      APP_DEBUG:
  #      APP_ENV:
  #      APP_URL:
  #      APP_KEY:
  #      DB_CONNECTION:
  #      DB_HOST:
  #      DB_PORT:
  #      DB_DATABASE:
  #      DB_USERNAME:
  #      DB_PASSWORD:
  #      QUEUE_CONNECTION:
  #      TWILIO_SID:
  #      TWILIO_AUTH_TOKEN:
  #      TWILIO_NUMBER:

  queue-worker:
    image: $CI_REGISTRY/$CI_PROJECT_PATH:${CI_COMMIT_SHORT_SHA}
    networks:
      - proxy_network
    command: php artisan queue:work
    environment:
      APP_DEBUG:
      APP_ENV:
      APP_URL:
      APP_KEY:
      DB_CONNECTION:
      DB_HOST:
      DB_PORT:
      DB_DATABASE:
      DB_USERNAME:
      DB_PASSWORD:
      FILESYSTEM_DISK:
      QUEUE_CONNECTION:
      TWILIO_SID:
      TWILIO_AUTH_TOKEN:
      TWILIO_NUMBER:

    deploy:
      replicas: ${REPLICAS}

networks:
  proxy_network:
    external: true
